### PR TITLE
own docker install

### PR DESCRIPTION
**Pull request by stefanwerfling**
for own dockerfile and call the post install self in docker entrypoint, benefit apt-get update and set in container start user and password

### CODE REVIEW

**Comment by stefanwerfling** [comment]
When merge my commit? For next package update is nice to have.

**Comment by ralfbecker** [comment]
Hi Stefan,

the debian.postinst in master is not up to date, the one in 17.1 branch is.

There is already some provisioning for a Docker installation under Univention:

https://github.com/EGroupware/egroupware/blob/17.1/doc/rpm-build/debian.postinst#L43

We could move that out into an own case for all Docker images not just Univention.

What do you think?

Ralf

**Comment by stefanwerfling** [comment]
I think that is a good idee. We should note between automatic installation (with postinst) or manual installtion. In the second case, can user start installation (with other sql server) or a own script in docker call the post instal with own parameter.

For my exsample, my docker images create all with "apt-get install" and then call a script the container with parameters, this script call the post install (post_install.php).

**Comment by ralfbecker** [comment]
I just commited the proposed change to 17.1:
https://github.com/EGroupware/egroupware/commit/414095b5f85dc243ae361f66ae8e278698d9806c

**Comment by nathangray** [comment]
Can this be closed?

**Comment by ralfbecker** [comment]
@stefanwerfling Can we close this now?

**Comment by ralfbecker** [comment]
Closing now as we offer Docker installation with 19.1

**Pull request closed without merging**
