### PR TITLE
* added share-link feature to filemanager context menu

### PR DESCRIPTION
**Pull request by WAMozart**

### CODE REVIEW

**Comment by ralfbecker** [comment]
@nathangray Can you have a look for this pull request, specially for how the link is inserted in the clipboard. I believe we have some code from you for that, which already used in the action system.

**Comment by nathangray** [comment]
There's a context menu command to copy the text of the current DOMNode to
the clipboard.
We used a different method, but their method seems to be supported across
current browser versions, and shorter.
http://caniuse.com/#feat=document-execcommand

The patch appears to work, though I wonder if this might go better as an
entry in the existing 'Share files' action instead of on its own.

**Comment by ralfbecker** [comment]
@nathangray you're right, it should be part of "Share files" sub-menu.
Can you merge the pull request, change the context menu and back-port it to 16.1.
Ralf

**Comment by nathangray** [comment]
Changed & backported

**Comment by WAMozart** [comment]
thanks guys!

**Pull request merged**
