### PR TITLE
Autoloading filemanager/cli.php

### PR DESCRIPTION
**Pull request by cit-gruenewald**
Unable to call ./filemanager/cli.php from cmd-line because classes won't be resolved since autoloading from cli doesn't work.

--> include_once for autoload.php

### CODE REVIEW

**Comment by ralfbecker** [comment]
Hi Jan,
thanks for all your efforts, we're currently very busy to get the stuff implemented, from which we think it's most helpful for the current home-office scenarios.
Therefore we're not as responsive as I would like it to be :( 
For that rather trivial patch, please remove DIRECTORY_SEPARATOR constant of simple forward slashes ("/"), which work on Windows too and which we use everywhere else, then I'll merge it directly.
Hope you understand
Ralf

**Comment by ralfbecker** [comment]
A simple workaround is also, just to authenticate with "--user root_admin --password ******", and the header also includes the autoloader. Probably the reason, why I never run into it.
Ralf

**Comment by cit-gruenewald** [comment]
> Hope you understand
Of course I do! 
> A simple workaround is also, just to authenticate with "--user root_admin --password ******", and the header also includes the autoloader.
That's true for `./filemanager/cli.php mount --user root_admin --password 'xxxx'`. Unfortunately that's not true (at least for me) as soon as I try to mount a specific URL.

**Comment by ralfbecker** [comment]
> That's true for ./filemanager/cli.php mount --user root_admin --password 'xxxx'. Unfortunately that's not true (at least for me) as soon as I try to mount a specific URL.

Mounting a specific URL requires ```--user root_admin --password 'xxxx'```, but shell also needs quotes around the mount-point / url argument, as it can contain eg. ampersands ("&").

Anyway it's merged now :)

Ralf

**Pull request merged**
