### PR TITLE
Bug in free/busy request handling (17.1)

### PR DESCRIPTION
**Pull request by nicorac**
This pull request fixes issues with free/busy calendar in Thunderbird Lightning (and possibly other) client.

Patch description here:
https://help.egroupware.org/t/bug-in-free-busy-request-handling-with-thunderbird-lightning-fixed-with-patch-attached/73300

### CODE REVIEW

**Comment by nicorac** [comment]
Sorry for a noob question but... are failed checks related to my changes?
As far as I can see they refer to files I haven't changed at all :(

**Comment by nathangray** [comment]
They do refer to files you haven't changed.  It looks like we haven't changed them recently either.   
preferences/index.php, for example, has not changed in 5 years.

You've based this off 17.1 branch.  Can you base it off master?

**Comment by nicorac** [comment]
I've based it on 17.1 because that's the version I'm running on production (available Ubuntu packages are 17.1.20181205).
Will port it to master.

**PS:** there's a **filename-case issue*** in eGroupware GIT repo:
* commit 1cbd0aa2a3a6a8ac8a57a644804493aed9383b4f (2018/10/19 by @hnategh)
  adds file `api/src/Etemplate/Widget/CKEditor.php`
  with class `CkEdiotr` (note the typo in class name)
* commit 44ef6a0a3010770a87006e00d4b2e31343f07846 (2018/10/23 by @hnategh)
  adds file `api/src/Etemplate/Widget/CkEditor.php` (note the different casing of **k** in filename)
  with class `CkEditor` (correct name)

Checking out `master` on Windows will always mark CkEditor.php (or CKEditor.php, depending of where we're coming from) as changed. On Linux there's no error **but** I get two different files and I don't know which is the right one to keep

I suppose the file to keep is the one in 44ef6a0a3010770a87006e00d4b2e31343f07846, with lowercase "k" and correct class name `CkEditor`.

**Comment by nicorac** [comment]
Ported to master in pull request #51.

Will next release (the one after 17.1.20181205) be based on `master` or `17.1` branch?
If the former then feel free to close this PR.

**Comment by nathangray** [comment]
Next release is going to be based on 17.1, so I manually backported.  For some reason it passed then.

**Comment by nicorac** [comment]
👌
Beware that you missed one change in your commit a1428d9f21ca7337a035eaab4984d2695a592483:
line 872 in file calendar/inc/class.calendar_groupdav.inc.php reads
`trim($attribute);`

This line is completely useless since trim() is a function and its parameter is not passed by reference.

**Comment by nathangray** [comment]
Thanks, removed it.

**Pull request closed without merging**
